apiVersion: apps/v1
kind: Deployment
metadata:
  name: top-secret
  labels:
    app: top-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: top-secret
  template:
    metadata:
      labels:
        app: top-secret
    spec:
      containers:
      - name: top-secret
        image: app
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi

