apiVersion: v1
kind: Service
metadata:
  name: top-secret
  labels:
    app: top-secret
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: top-secret
